package com.github.joncros.random_word;

/**
 * 
 *
 */
public class CLI implements RandomWordUI
{
    /*
     * Desired functionality: print each letter as it is chosen by RandomWord. If a letter has to be replaced,
     * print a newline, reprint previous letters and print the new letter.
     */

    /**
     * Prints the character to standard output
     * @param c a single char
     */
    public void display(char c) {
        System.out.print(c);
    }

    /**
     * Prints the String to a new line on standard out
     * @param s the current word
     */
    public void display(String s) {
        System.out.print("\n" + s);
    }

    /**
     * Called to display the final generated word
     * @param s The complete word generated by RandomWord
     */
    @Override
    public void displayFinalWord(String s, int startIndex) throws InterruptedException {
        for (int i = startIndex; i < s.length(); i++) {
            System.out.print(s.charAt(i));
            Thread.sleep(250);
        }
        System.out.println("\nThe word is " + s);
    }
}
