package com.github.joncros.random_word;

/**
 * 
 *
 */
public class CLI implements RandomWordUI
{
    public static void main( String[] args )
    {
        
    }

    /**
     * Displays the current word generated by RandomWord
     * @param s the current word
     */
    public void display(String s) {

    }

    /**
     * Called by RandomWord to indicate it has finished generating the word
     * @param s The complete word generated by RandomWord
     */
    public void finish(String s) {
        //print "The word is " + s
    }
}
