package com.github.joncros.random_word;

public interface RandomWordUI {

    /**
     * Called to display the next character of the word being assembled
     * @param c a single char
     */
    void display(char c);

    /**
     * Called to display the word so far. Intended for use after a letter has been replaced
     * @param s the current word
     */
    void display(String s);

    /**
     * Called to display the final generated word
     * @param s The complete word generated by RandomWord
     */
    void displayFinalWord (String s);
}
