package com.github.joncros.random_word;

public interface RandomWordUI {

    /**
     * Called to display the next character of the word being assembled
     * @param c a single char
     */
    void display(char c);

    /**
     * Called to display the word so far. Intended for use after a letter has been replaced
     * @param s the current word
     */
    void display(String s);

    /**
     * Called to display the final generated word. Displays each character in the word starting
     * at startIndex.
     * @param s The complete word generated by RandomWord
     * @param startIndex The index of the first character in s to display
     * @throws InterruptedException so that implementing classes can cause the thread to sleep in
     * between each character (for dramatic effect) rather than printing all the characters instantly
     */
    void displayFinalWord (String s, int startIndex) throws InterruptedException;
}
